//
//  NSKAuthMethodGuest.h
//  NVIDIAStreamKit
//
//  Created by James Howard on 12/5/23.
//  Copyright © 2023 NVIDIA CORPORATION. All rights reserved.
//

#import <NVIDIAStreamKit/NSKAuthMethod.h>

NS_ASSUME_NONNULL_BEGIN

//! Configuration for a Guest Mode session.
@interface NSKGuestModeRequest : NSObject

//! Hostname of the Guest Mode token server. Defaults to the value of the NSUserDefaults key `NSKAccountLinkingServiceHost`.
@property (copy) NSString *host;

//! GDN Partner ID.
@property (copy) NSString *partnerIdentifier;

//! Guest Mode nonce.
//! This is an opaque value generated by the partner service that authorizes access.
//! Note that a nonce can only be used one time for one streaming session.
@property (copy) NSString *nonce;

//! Unique device identifier (optional).
@property (copy, nullable) NSString *deviceIdentifier;

//! The identifier of the remote application that the session will launch.
//! This must match the cms identifier used when creating the nonce AND it must match the appId in the NSKStreamConfiguration used to start the streaming session.
@property (copy) NSNumber *cmsIdentifier;

@end

//! Represents a one time use Guest Mode authentication session for use with NVIDIA GDN.
//! Each instance can be used just once with ``NSKStreamConfiguration`` to start a single session with ``NSKStreamClient``.
//!
//! See the [GDN Guest Mode Integration Guide](https://docs.google.com/document/d/1Ry74FOoXP0203DMRjeFNMaePAK3tC-SqSDP3iZ_N04U/edit?usp=sharing) for more info.
@interface NSKAuthMethodGuest : NSObject <NSKAuthMethod, NSSecureCoding>

//! Redeem a Guest Mode nonce for a session token.
//! - parameter request: Contains the Guest Mode nonce and other session configuration parameters.
//! - parameter completionHandler: Called on the main queue when redemption of the nonce for a token succeeds, fails, or is cancelled..
//! - returns: An indeterminate NSProgress object that may be used to cancel the network operation.
+ (NSProgress *)performLoginWithRequest:(NSKGuestModeRequest *)request
                    completionHandler:(void (^)(NSKAuthMethodGuest * _Nullable guestAuth, NSError * _Nullable error))completion;

//! The cms identifier for the application that the token will be used to launch.
@property (readonly) NSNumber *cmsIdentifier;

@end

/// NSError domain for errors from the Guest Mode auth subsystem.
extern NSString *const NSKAuthMethodGuestErrorDomain;

// NSError codes for errors from the Guest Mode auth subsystem.
typedef NS_ENUM(NSInteger, NSKAuthMethodGuestErrorCode) {
    //! Invalid NSKGuestModeRequest configuration.
    NSKAuthMethodGuestErrorCodeRequest = 1,
    //! Error communicating with server (unexpected/no response)
    NSKAuthMethodGuestErrorCodeServer,
    //! Account Linking Server reports invalid nonce or nonce does not match partner identifier or cms identifier.
    NSKAuthMethodGuestErrorCodeNonce,
};

NS_ASSUME_NONNULL_END
