#!/bin/bash

# Mostly generated by ChatGPT 4o
# anwilson 2024-08-28

# Variables
REPO_URL="ssh://git@gitlab-master.nvidia.com:12051/cloudxr/cloudxr-apple.git"
TARGET_DIR="dependencies/development/cloudxr-apple"

# This should make this script exit immediately if any command in this script has nonzero exit code
set -e

# Check if the target directory exists
if [ -d "$TARGET_DIR" ]; then
    echo "Directory $TARGET_DIR exists. Checking if it's a clone of $REPO_URL..."
    
    # Check if the directory is a git repository
    if [ -d "$TARGET_DIR/.git" ]; then
        # Get the URL of the origin remote
        CURRENT_URL=$(git -C "$TARGET_DIR" config --get remote.origin.url)
        
        if [ "$CURRENT_URL" == "$REPO_URL" ]; then
            echo "Directory $TARGET_DIR is already a clone of $REPO_URL. Updating..."
            # Attempt to update the repository and its submodules
            git -C "$TARGET_DIR" checkout main
            git -C "$TARGET_DIR" pull --recurse-submodules
            # TODO: Remove this and have a version file, or other mechanism.
            git -C "$TARGET_DIR" checkout 7a7be1d33dd114c0b535d8de61ed3b7eb2691bb8
        else
            echo "Directory $TARGET_DIR exists but is not a clone of $REPO_URL."
            exit 1
        fi
    else
        echo "Directory $TARGET_DIR exists but is not a Git repository."
        exit 1
    fi
else
    echo "Directory $TARGET_DIR does not exist. Attempting to clone $REPO_URL..."
    
    # Attempt to clone the repository
    git clone --recurse-submodules "$REPO_URL" "$TARGET_DIR"
    git -C "$TARGET_DIR" checkout 7a7be1d33dd114c0b535d8de61ed3b7eb2691bb8
    
    echo "Repository cloned successfully into $TARGET_DIR."
fi

git -C "$TARGET_DIR" submodule update --init --recursive 
echo "Submodules updated successfully."

pushd "$TARGET_DIR"

/opt/homebrew/bin/python3 ./scripts/fetch-balmung-xcframeworks.py 
./scripts/build-cloudxr-xcframework.sh 

popd

XC_FRAMEWORK_OUT=./VFISample/XCFrameworks
mkdir -p -- "$XC_FRAMEWORK_OUT"
cp -R ./dependencies/development/cloudxr-apple/XCFrameworks/* "$XC_FRAMEWORK_OUT"
